#!/bin/bash
sed -i "s/NAMENODE/$1/g" $HADOOP_HOME/etc/hadoop/core-site.xml 
chown hdfs $HADOOP_HOME/etc/hadoop/core-site.xml 
sudo -u hdfs HADOOP_HOME=$HADOOP_HOME $HADOOP_HOME/bin/hdfs namenode -format -nonInteractive -force
sudo -u hdfs HADOOP_HOME=$HADOOP_HOME $HADOOP_HOME/sbin/start-dfs.sh