#!/bin/bash
export SPARK_HOME=/spark-2.1.0-bin-hadoop2.7
#/spark-1.6.1-bin-hadoop2.6/sbin/start-master.sh -h $1
/spark-2.1.0-bin-hadoop2.7/bin/spark-class org.apache.spark.deploy.master.Master --ip $1 --port 7077 --webui-port 8080
