#!/bin/bash
export SPARK_HOME=/spark-2.1.0-bin-hadoop2.7
#/spark-1.6.1-bin-hadoop2.6/sbin/start-slave.sh -h $2 -p $3 spark://$1:7077
/spark-2.1.0-bin-hadoop2.7/bin/spark-class org.apache.spark.deploy.worker.Worker -i $2 -p $3 spark://$1:7077