#!/bin/bash
export SPARK_HOME=/spark-2.2.1-bin-hadoop2.7
sed -i "s/NAMENODE/$2/g" $HADOOP_HOME/etc/hadoop/core-site.xml
chown hdfs $HADOOP_HOME/etc/hadoop/core-site.xml 
rm /home/hdfs/.ssh/id_rsa*
mkdir -p /home/hdfs/.ssh
chown hdfs /home/hdfs/.ssh
runuser -l hdfs -c "ssh-keygen -N '' -t rsa -f ~/.ssh/id_rsa"
cp /home/hdfs/.ssh/id_rsa.pub /var/www/ananke/static/id_rsa.pub
cp $HADOOP_HOME/etc/hadoop/core-site.xml /var/www/ananke/static/core-site.xml
chmod a+r /var/www/ananke/static/id_rsa.pub
sudo -u hdfs HADOOP_HOME=$HADOOP_HOME $HADOOP_HOME/bin/hdfs namenode -format -nonInteractive -force
/spark-2.2.1-bin-hadoop2.7/bin/spark-class org.apache.spark.deploy.master.Master --ip $1 --port 7077 --webui-port 8080
